### ISSUE TITLE
Falsche DB?

### ISSUE THREAD

**Issue by krichenbauer** [hoe-si/new#2]
Gegeben: die aktuelle Instanz auf hoesidollar.de

Arbeitsschritte: Das ./timerun.py wird ausgeführt

Erwartetes Verhalten: Das Script bezieht seine Daten aus der mysql-tabelle und bearbeitet diese auch.

Verhalten: Offenbar greift das script nur auf die sqlight zu...

**Comment by krichenbauer** [comment]
Ich habe das in commit b9b7ae5 behoben. Bitte überprüfen, ob das so passt und anschließend diesen Issue schließen.

**Comment by network4u** [comment]
Sollte so passen. Was mich wundert ist, dass zuvor die falsche db ausgewählt wurde, da die db- Variable später im Quelltext überschrieben wird
