### ISSUE TITLE
Mindestlohn wird bei zu geringen Steuern nicht ausgezahlt.

### ISSUE THREAD

**Issue by krichenbauer** [hoe-si/new#3]
Gegeben: aktuelle Instanz auf hoesidollar.de

Arbeitsschritte:
1. Schüler führen einige Transaktionen an Firmen aus
2. das ./timerun.py wird ausgeführt. Dieses schlägt einen Steuersatz deutlich über 100% vor.
3. ich lege einen Steuersatz von 15% fest

Erwartetes Verhalten:
In Firmen, in denen der Mindestlohn nicht aus dem Kontostand der Firma oder den Steuern finanziert werden kann wird trotzdem der Mindestlohn aus dem Staatshaushalt entnommen (erzeugt), damit wirklich jeder den Mindestlohn bekommt.

Verhalten:
Viele Schüler bekamen nur 1 HöSi ausbezahlt. (Siehe Transaktionen zur Zeit 1531812654)

**Comment by krichenbauer** [comment]
Da stellt sich mir auch gleich die Frage, was passiert, wenn ich deinen Steuersatz oberhalb des vorgeschlagenen auswähle

**Comment by network4u** [comment]
Steuersatz oberhalb des Vorschlages: Das Geld wird für die nächste Mindestlohnauszahlung aufgehoben. Der nächste Steuervorschlag fällt entsprechend geringer aus
Der Fehler müsste außerdem unabhängig vom nach unten korrigierten Steuersatz auftreten, da (Siehe bug zu negativen überweisungen) der Kontostand des Geschäftes (fehlerhafter Weise) schon vor der Überweisung von Konto 0 abgefragt wurde, der Zuschuss von Konto 1 entsprechend vor der Fehlerbehebung keinen Einfluss auf die Lohnauszahlung hatte
