### ISSUE TITLE
Negative Lohnzahlungen

### ISSUE THREAD

**Issue by krichenbauer** [hoe-si/new#4]
Gegeben: aktuelle Instanz auf hoesidollar.de

Arbeitsschritte:
1. Die Konten der Firmen verfügen über stark unterschiedliche Kontostände (20000: 3000H$, 20001 und 20002 ca. 50H$)
2. Das ./timerun.py wird ausgeführt
3. Der vorgeschlagene Steuersatz wird gewählt

Erwartetes Verhalten:
Jeder bekommt entweder den Mindestlohn oder einen größeren Betrag ausgezahlt.

Verhalten:
Die Konten der Mitarbeiter der "Pleitefirmen" bekommen negative Transaktionen. (Siehe Transaktionen zum Zeitpunkt 1531813077)

**Comment by network4u** [comment]
Bug kam durch ein Verfrühtes Abfragen des Gruppenkontostandes zu Stande, ist jetzt aber gefixt
